version: "3"

networks:
  technical_task:

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: technicalTask_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_HOST=%
    networks:
      - technical_task
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        compress: "true"
  ngx:
    container_name: webtechnicalTask_nginx
    image: nginx:1.20-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/ngx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - technical_task

  php:
    container_name: webtechnicalTask_php
    volumes:
      - .:/var/www/html
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - technical_task
